### PR TITLE
Fix DENTRY-usage in 16-vmhgfs-9.6.2

### PR DESCRIPTION
**Pull request by hurda**

### CODE REVIEW

**Comment by rasa** [comment]
This patch looks good, but I'm concerned that the original patch may work for some versions of VMware Tools, and your "patch" should really be a separate file for the version you are using. Do you concur?

**Comment by hurda** [comment]
The issue I reported and the original patch are for 9.6.2.
I could test the patch with the vmware-tools between 9.6.2 and 9.9.2 (for which patch 13-vmhgfs was made), if it helps.
Maybe it's also a matter of the used gcc-version.

**Comment by hurda** [comment]
I tested the original patch with Ubuntu 15.04 (gcc 4.9.2) and vmware-tools 9.6.2, and it's compiling successfully.
Then I tried again with my modifications, and the compilation worked too.
I guess gcc 4.8.2 of Ubuntu 14.04 doesn't like the way DENTRY() is used in the original 16-vmhgfs-9.6.2-patch.

**Comment by rasa** [comment]
If you'll submit a new PR for a new file, say `16-vmhgfs-f_dentry-kernel-3.19.0-15-tools-9.6.2-gcc-4.8.2.patch`, I'll happily accept it. Thanks for all the research.

**Comment by hurda** [comment]
Fixed in #59

**Pull request closed without merging**
